services:

  app:
    image: huatri/pes_container
    container_name: springboot_container
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: jdbc:mysql://171.244.198.239:3306/pesswd2025
      MYSQL_USER: "dbadmin"
      MYSQL_PASSWORD: "Huatrideptrai#1"
      TZ: Asia/Ho_Chi_Minh
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Ho_Chi_Minh"
